runtime: nodejs14

automatic_scaling:
  min_instances: 0
  max_instances: 1
resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto